config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => {:sessions => 'users/sessions', :registrations => 'users/registrations'}

  root :to => 'application#home'
  post 'confirm' => 'confirmation_partials#confirm'
  get 'home' => 'application#home'
  get 'students' => 'application#students'
  get 'students/:branch' => 'application#students'
  get 'requests' => 'application#requests'
  get 'requests/:branch' => 'application#requests'
  post 'pending_status' => 'application#pending_status'
  post 'destroy' => 'application#destroy'
  get 'index' => 'static#index'

end

app/views/layouts/_footer.html.erb
        <%= javascript_include_tag "_con/js/_demo.js" %>
        <%= javascript_include_tag "js/script.js" %>
        <%= javascript_include_tag "markitup/sets/default/set.js" %>
        <%= javascript_include_tag "pace.min.js" %>
        <%= stylesheet_link_tag "markitup/skins/_con/style.css" %>
        <%= stylesheet_link_tag "markitup/sets/default/style.css" %>
        <%= stylesheet_link_tag "pace.css" %>
        <div class="paceDiv"></div>

app/views/layouts/_head.html.erb
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title><%=@title%></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <%= stylesheet_link_tag "fonts.googleapis.com/css4ec9.css?family=Roboto:400,100,300,500,700,900" %>
        <%= stylesheet_link_tag "css/style.css" %>
	    <%= csrf_meta_tags %>
	    <%#= javascript_include_tag "application_header.js" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <%= render partial: 'layouts/head' %>
        <style>
        .demo-toggle {
        	display:none;
        }
        </style>
    </head>

    <body>
	    <nav class="navbar-top navbar-dark">
	        <div class="nav-wrapper">
	            <a href="#" class="yay-toggle">
	                <div class="burg1"></div>
	                <div class="burg2"></div>
	                <div class="burg3"></div>
	            </a>
	            <a href="#!" class="brand-logo"><img alt=""></a>
	            <ul>
	                <!-- <li><a href="#!" class="search-bar-toggle"><i class="mdi-action-search"></i></a></li> -->
	                <li class="user">
	                    <a class="dropdown-button" href="#!" data-activates="user-dropdown"><%= image_tag current_user.avatar.url, class: "circle", alt: current_user.first_name + " " + current_user.last_name, width: "35px", height: "35px" %><%=current_user.first_name + " " + current_user.last_name%><i class="mdi-navigation-expand-more right"></i></a>
	                    <ul id="user-dropdown" class="dropdown-content">
	                        <li><a href="/users/edit"><i class="fa fa-edit"></i> Edit Profile</a></li>
	                        <li class="divider"></li>
	                        <li>
								<%= link_to destroy_session_path(:user), :method => :delete do %>
									Logout <i class="ion-log-out"></i>
								<% end %>
	                        </li>
	                    </ul>
	                </li>
	            </ul>
	        </div>
	    </nav>
	    <aside class="yaybar yay-shrink yay-hide-to-small yay-gestures">
	        <div class="top">
	            <div>
	                <a href="#" class="yay-toggle">
	                    <div class="burg1"></div>
	                    <div class="burg2"></div>
	                    <div class="burg3"></div>
	                </a>
	                <a href="#!" class="brand-logo"><img src="assets/_con/images/logo-white.png" alt="Con"></a>
	            </div>
	        </div>
	        <div class="nano">
	            <div class="nano-content">
	                <ul>
	                    <li class="label">Menu</li>
	                    <li><a class="yay-sub-toggle waves-effect waves-blue"><i class="fa fa-dashboard"></i> Dashboard<span class="yay-collapse-icon mdi-navigation-expand-more"></span></a>
	                        <ul>
	                            <li><a href="/home" class="waves-effect waves-blue"><i class="fa fa-user"></i>Profile</a></li>
	                        </ul>
	                    </li>
	                    <% if current_user.admin? %>
	                    <li class="label">View</li>
	                    <li><a class="yay-sub-toggle waves-effect waves-blue"><i class="fa fa-indent"></i> Students<span class="yay-collapse-icon mdi-navigation-expand-more"></span></a>
	                        <ul>
	                            <li><a href="/students/" class="waves-effect waves-blue"><i class="fa fa-group"></i>All</a></li>
                                <li><a class="yay-sub-toggle waves-effect waves-blue" href="#!"><i class="fa fa-gears"></i>Departments<span class="yay-collapse-icon mdi-navigation-expand-more"></span></a>
                                    <ul>
                                    	<% @department_list.each_key do |key| %>
                                        <li><a href="/students/<%=@department_list[key]%>" class="waves-effect waves-blue"><%=key%></a></li>
                                    	<% end %>
                                    </ul>
                                </li>
	                        </ul>
	                    </li>
	                    <li class="label">Actions</li>
	                    <li><a class="yay-sub-toggle waves-effect waves-blue"><i class="mdi-action-done-all"></i> Requests<span class="yay-collapse-icon mdi-navigation-expand-more"></span>
	                    <% if @requests_all > 0 %>
	                    <span class="badge new"><%=@requests_all%></span>
	                    <% end %>
	                    </a>
	                        <ul>
	                            <li><a href="/requests/" class="waves-effect waves-blue"><i class="mdi-content-select-all"></i>All</a></li>
                                <li><a class="yay-sub-toggle waves-effect waves-blue" href="#!"><i class="fa fa-gears"></i>Departments<span class="yay-collapse-icon mdi-navigation-expand-more"></span></a>
                                    <ul>
                                    	<% index = 0 %>
                                    	<% @department_list.each_key do |key| %>
                                        <li><a href="/requests/<%=@department_list[key]%>" class="waves-effect waves-blue"><%=key%>
					                    <% if @requests_list[index] > 0 %>
					                    <span class="badge new"><%=@requests_list[index]%></span>
					                    <%
					                    	end
					                    	index += 1
					                    %>
                                        </a></li>
                                    	<% end %>
                                    </ul>
                                </li>
	                        </ul>
	                    </li>
	                    <% end %>
	                </ul>
	            </div>
	        </div>
	    </aside>
	    <section class="content-wrap">
	        <div class="page-title">
	            <div class="row">
	                <div class="col s12 m9 l10">
	                <%= yield :breadcrumbs %>
	                </div>
	            </div>
	        </div>
            <%=yield%>
	    </section>
	    </div>
	    <footer>&copy; 2015 <strong>Archit Srivastava</strong>. All rights reserved.</footer>
        <%= render partial: 'layouts/footer' %>
        <%= yield :scripts %>
    </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
    <head>
        <%= render partial: 'layouts/head' %>
    </head>

    <body>
        <section id="sign-up">
        <%= yield %>
        </section>
        <%= render partial: 'layouts/footer' %>
        <%= yield :scripts %>
    </body>
</html>